PRODUCT_VERSION_MAJOR = 21
PRODUCT_VERSION_MINOR = 0

ifeq ($(AOSPENHANCED_VERSION_APPEND_TIME_OF_DAY),true)
    AOSPENHANCED_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    AOSPENHANCED_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set AOSPENHANCED_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef AOSPENHANCED_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "AOSPENHANCED_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^AOSPENHANCED_||g')
        AOSPENHANCED_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(AOSPENHANCED_BUILDTYPE)),)
    AOSPENHANCED_BUILDTYPE := UNOFFICIAL
    AOSPENHANCED_EXTRAVERSION :=
endif

ifeq ($(AOSPENHANCED_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        AOSPENHANCED_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

AOSPENHANCED_VERSION_SUFFIX := $(AOSPENHANCED_BUILD_DATE)-$(AOSPENHANCED_BUILDTYPE)$(AOSPENHANCED_EXTRAVERSION)-$(AOSPENHANCED_BUILD)

# Internal version
AOSPENHANCED_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(AOSPENHANCED_VERSION_SUFFIX)

# Display version
AOSPENHANCED_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(AOSPENHANCED_VERSION_SUFFIX)
